@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}
@refreshToken = {{authenticate.response.body.refreshToken}}

# RECADOS
### Lista todos os recados
GET {{baseUrl}}/message/
?limit=10
&offset=0
### Lista apenas um recado
GET {{baseUrl}}/message/2/
### Cria um recado
POST {{baseUrl}}/message/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "content": "Olá, tudo bem?",
    "toId": 15
}
### Atualiza um recado
PATCH {{baseUrl}}/message/15/
Content-Type: application/json

{
    "content": "Atualizando recado",
    "isRead": false
}
### Apaga um recado
DELETE {{baseUrl}}/message/12/


# Users
### Lista todas os users
GET {{baseUrl}}/users/?limit=10&offset=0
Authorization: Bearer {{authToken}}

### Lista apenas um usuário
GET {{baseUrl}}/users/12/
Authorization: Bearer {{authToken}}


### Cria um usuário
POST {{baseUrl}}/users/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "email": "email2@email.com",
    "password": "123456",
    "name": "Camis"
}

### Apaga um usuário
DELETE {{baseUrl}}/users/10/
Authorization: Bearer {{authToken}}

### Atualiza um usuário
PATCH {{baseUrl}}/users/17/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "password": "12345A",
    "name": "Camis"
}


# AUTH
### Autenticação
# @name authenticate
POST {{baseUrl}}/auth/
Content-Type: application/json

{
    "email": "email2@email.com",
    "password": "12345A"
}
### Re-Autenticação
# @name reAuthenticate
POST {{baseUrl}}/auth/refresh/
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}