@baseUrl = http://localhost:3000

# RECADOS
### Lista todos os recados
GET {{baseUrl}}/message/
?limit=10
&offset=0
### Lista apenas um recado
GET {{baseUrl}}/message/2/
### Cria um recado
POST {{baseUrl}}/message/
Content-Type: application/json

{
    "content": "NOVO Recado",
    "from": "Joana",
    "to": "João"
}
### Atualiza um recado
PATCH {{baseUrl}}/message/4/
Content-Type: application/json

{
    "content": "Atualizando recado",
    "isRead": true
}
### Apaga um recado
DELETE {{baseUrl}}/message/3/
