@baseUrl = http://localhost:3000

# RECADOS
### Lista todos os recados
GET {{baseUrl}}/message/
?limit=10
&offset=0
### Lista apenas um recado
GET {{baseUrl}}/message/15/
### Cria um recado
POST {{baseUrl}}/message/
Content-Type: application/json

{
    "content": "Olá, tudo bem?",
    "fromId": 12,
    "toId": 15
}
### Atualiza um recado
PATCH {{baseUrl}}/message/15/
Content-Type: application/json

{
    "content": "Atualizando recado",
    "isRead": false
}
### Apaga um recado
DELETE {{baseUrl}}/message/3/


# Users
### Lista todas os users
GET {{baseUrl}}/users/
?limit=10
&offset=0
### Lista apenas uma pessoa
GET {{baseUrl}}/users/10/
### Cria uma pessoa
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "email": "email1@email.com",
    "password": "123456",
    "name": "Camis"
}
### Apaga um usuário
DELETE {{baseUrl}}/users/10/

### Atualiza um usuário

PATCH {{baseUrl}}/users/10/
Content-Type: application/json

{
    "password": "12345A",
    "name": "Camis"
}
